In [3]:
import numpy as np

In [2]:
# Step 1: create list of numbers
my_list = [5, 10, 15, 20]

# Step 2: convert list into NumPy array
my_array = np.array(my_list)

# Step 3: Print array to see result
print("NumPy Array: ", my_array)

NumPy Array:  [ 5 10 15 20]


In [3]:
# Multi-dimensional
# Step 1: create nested list
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
nested_list = [[a,b,c],[a,b,c],[a,b,c]]
matrix = np.array(nested_list)
print(matrix)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
#array inspection
print("Shape of matrix: ", matrix.shape)    # dimensions (number of rows)
print("Total elements: ", matrix.size)      # Number of elements
print("Data Type: ", matrix.dtype)          # Type of elements

Shape of matrix:  (3, 3, 3)
Total elements:  27
Data Type:  int64


In [5]:
# array creation
zeroes = np.zeros((3,4,5))
ones = np.ones((2,5))
randoms = np.random.rand(3,3)
print(zeroes)
print(ones)
print(randoms)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.77574708 0.12713069 0.70781545]
 [0.24858964 0.71731784 0.16600647]
 [0.26678382 0.62841175 0.24147813]]


In [7]:
#Changing data types
float_array = np.array([1,2,3], dtype = float)
print("Array with floats: ", float_array, " Data Type: ",float_array.dtype)

Array with floats:  [1. 2. 3.]  Data Type:  float64


In [6]:
# Define two arrays of the same shape
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1 + array2)
print(array2 - array1)
print(array1 * array2)
print(array2 / array1)
print(array2 % array1)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[0 1 0]


In [7]:
# Scalar operations
print(array1 * 3)

[3 6 9]


In [8]:
# Broadcastng: making arrays owith different shapes compatible for element-wise operations i.e. adding 1D array to 2D array
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([10,20,30])
print(matrix+vector)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
